### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by somuthink** [abionics/UltraLight#1]
Sorry this isn't an issue, but how can I select CPU or GPU rendering for detecting faces?

**Comment by abionics** [comment]
Hi! This model uses ONNX backend, so:
1) Replace onnxruntime
```
pip uninstall onnxruntime
pip install onnxruntime-gpu
```
2) Pass 'CUDAExecutionProvider' as provider
```
detector = UltraLightDetector(providers=['CUDAExecutionProvider'])
```
